[2019-11-17 21:14:48,277] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [queued]>
[2019-11-17 21:14:48,281] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [queued]>
[2019-11-17 21:14:48,281] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 21:14:48,281] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-11-17 21:14:48,281] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 21:14:48,286] {taskinstance.py:859} INFO - Executing <Task(QualityCheckOperator): Run_data_quality_checks> on 2018-11-03T06:00:00+00:00
[2019-11-17 21:14:48,286] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'dend_dag', 'Run_data_quality_checks', '2018-11-03T06:00:00+00:00', '--job_id', '306', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dend_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmp0a8jssih']
[2019-11-17 21:14:48,941] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 21:14:48,942] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   """)
[2019-11-17 21:14:49,015] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks [2019-11-17 21:14:49,015] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 21:14:49,291] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks [2019-11-17 21:14:49,290] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/dend_dag.py
[2019-11-17 21:14:49,304] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks [2019-11-17 21:14:49,304] {cli.py:516} INFO - Running <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 21:14:49,311] {quality_check.py:20} INFO - QualityCheckOperator for ['staging_versions', 'staging_dependencies', 'staging_projects', 'repository_fact', 'version_dim', 'dependency_dim', 'project_dim', 'time_dim']
[2019-11-17 21:14:49,316] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:14:49,315[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:14:56,920] {quality_check.py:29} INFO - data quality check on staging_versions check passed with 27069315 records
[2019-11-17 21:14:56,925] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:14:56,925[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:15:03,988] {quality_check.py:29} INFO - data quality check on staging_dependencies check passed with 153719958 records
[2019-11-17 21:15:03,993] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:15:03,992[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:15:12,591] {quality_check.py:29} INFO - data quality check on staging_projects check passed with 6645753 records
[2019-11-17 21:15:12,595] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:15:12,595[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:15:15,765] {taskinstance.py:1051} ERROR - data quality check failed, repository_fact contains no records
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/quality_check.py", line 28, in execute
    raise ValueError(f"data quality check failed, {table} contains no records")
ValueError: data quality check failed, repository_fact contains no records
[2019-11-17 21:15:15,769] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks Traceback (most recent call last):
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     args.func(args)
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     return f(*args, **kwargs)
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     _run(args, dag, ti)
[2019-11-17 21:15:15,780] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     pool=args.pool,
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     return func(*args, **kwargs)
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     result = task_copy.execute(context=context)
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks   File "/Users/likejun/airflow/plugins/operators/quality_check.py", line 28, in execute
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks     raise ValueError(f"data quality check failed, {table} contains no records")
[2019-11-17 21:15:15,781] {base_task_runner.py:115} INFO - Job 306: Subtask Run_data_quality_checks ValueError: data quality check failed, repository_fact contains no records
[2019-11-17 21:15:18,322] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:15:18,322[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
