[2019-11-17 21:22:40,388] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [queued]>
[2019-11-17 21:22:40,395] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [queued]>
[2019-11-17 21:22:40,395] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 21:22:40,395] {taskinstance.py:839} INFO - Starting attempt 3 of 4
[2019-11-17 21:22:40,395] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-11-17 21:22:40,399] {taskinstance.py:859} INFO - Executing <Task(QualityCheckOperator): Run_data_quality_checks> on 2018-11-03T06:00:00+00:00
[2019-11-17 21:22:40,399] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'dend_dag', 'Run_data_quality_checks', '2018-11-03T06:00:00+00:00', '--job_id', '308', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dend_dag.py', '--cfg_path', '/var/folders/8q/nyxhvd6d55nfqjdbrybk6jpw0000gn/T/tmpcppx54gx']
[2019-11-17 21:22:41,069] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks /Users/likejun/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
[2019-11-17 21:22:41,069] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   """)
[2019-11-17 21:22:41,146] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks [2019-11-17 21:22:41,145] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-17 21:22:41,428] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks [2019-11-17 21:22:41,428] {dagbag.py:90} INFO - Filling up the DagBag from /Users/likejun/airflow/dags/dend_dag.py
[2019-11-17 21:22:41,443] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks [2019-11-17 21:22:41,443] {cli.py:516} INFO - Running <TaskInstance: dend_dag.Run_data_quality_checks 2018-11-03T06:00:00+00:00 [running]> on host likejundeMacBook-Pro.local
[2019-11-17 21:22:41,452] {quality_check.py:20} INFO - QualityCheckOperator for ['staging_versions', 'staging_dependencies', 'staging_projects', 'repository_fact', 'version_dim', 'dependency_dim', 'project_dim', 'time_dim']
[2019-11-17 21:22:41,459] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:22:41,458[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:22:50,650] {quality_check.py:29} INFO - data quality check on staging_versions check passed with 27069315 records
[2019-11-17 21:22:50,655] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:22:50,655[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:22:56,180] {quality_check.py:29} INFO - data quality check on staging_dependencies check passed with 153719958 records
[2019-11-17 21:22:56,185] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:22:56,184[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:23:00,431] {quality_check.py:29} INFO - data quality check on staging_projects check passed with 6645753 records
[2019-11-17 21:23:00,435] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:23:00,435[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster.chjcdyihped1.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-11-17 21:23:05,423] {taskinstance.py:1051} ERROR - data quality check failed, repository_fact contains no records
Traceback (most recent call last):
  File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/likejun/airflow/plugins/operators/quality_check.py", line 28, in execute
    raise ValueError("data quality check failed, {} contains no records".format(table))
ValueError: data quality check failed, repository_fact contains no records
[2019-11-17 21:23:05,424] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks Traceback (most recent call last):
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/bin/airflow", line 32, in <module>
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     args.func(args)
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     return f(*args, **kwargs)
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     _run(args, dag, ti)
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     pool=args.pool,
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     return func(*args, **kwargs)
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     result = task_copy.execute(context=context)
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks   File "/Users/likejun/airflow/plugins/operators/quality_check.py", line 28, in execute
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks     raise ValueError("data quality check failed, {} contains no records".format(table))
[2019-11-17 21:23:05,433] {base_task_runner.py:115} INFO - Job 308: Subtask Run_data_quality_checks ValueError: data quality check failed, repository_fact contains no records
[2019-11-17 21:23:10,426] {logging_mixin.py:95} INFO - [[34m2019-11-17 21:23:10,425[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
